# example config file




# organization behavior
zip_behavior = "KEEP"
backup_behavior = "COPY"
preserve_modules = true
levels_to_preserve = 1
preserve_creators = true

# file structure - basic
["folders"]
input = "path"
output = "path"
zip_backup = "path"
intermediate = "path"

# file structure - with root
root_folder = "path/to/root"
# input_folder = "input"

[creators]
CzePeku = "$5 Rewards"
Limithron = ["Admiral", "Captain"]

[folder_renames]
"The Clean" = "Clean"
The = ""

trim_words = ["ItW"]
skip_grouping = ["The", "Elves"]

