file_name_exceptions:
  The Clean: Clean
  The: ""
replace_exceptions:
  ItW: ""
clean_exceptions:
  - 5e
should_ignore:
  - __MACOSX
  - .DS_Store
  - Thumbs.db
  - .AppleDouble
  - .LSOverride
  - desktop.ini
  - .fseventsd
  - .Spotlight-V100
  - .TemporaryItems
  - .Trashes
  - .DocumentRevisions-V100
  - thumbs
